; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
board_build.partitions = default.csv

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize

lib_deps =
  ESP32Async/AsyncTCP @ ^3.3.2
  ESP32Async/ESPAsyncWebServer @ ^3.6.0
  bblanchon/ArduinoJson @ ^7.0.4

build_flags =
  -D CORE_DEBUG_LEVEL=3
  -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
  -D CONFIG_ASYNC_TCP_STACK_SIZE=4096

lib_ldf_mode = deep+